#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 100
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 1
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5

enum {
  sym_name = 1,
  anon_sym_COLON = 2,
  anon_sym_EQ = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  sym_operator = 8,
  anon_sym_BSLASH = 9,
  anon_sym_DASH_GT = 10,
  anon_sym__ = 11,
  anon_sym_DQUOTE = 12,
  aux_sym_string_token1 = 13,
  anon_sym_BSLASH_LPAREN = 14,
  sym_string_escaped = 15,
  sym_number = 16,
  sym_no_value = 17,
  sym_comment = 18,
  sym_import_keyword = 19,
  anon_sym_SEMI = 20,
  sym__newline = 21,
  sym_source_file = 22,
  sym__statement = 23,
  sym_import = 24,
  sym_declaration = 25,
  sym_definition = 26,
  sym__expression = 27,
  sym__record = 28,
  sym_record_declaration = 29,
  sym_record_definition = 30,
  sym__function_call = 31,
  sym_prefix_call = 32,
  sym_infix_call = 33,
  sym_operator_expression = 34,
  sym_function = 35,
  sym_pattern = 36,
  sym__grouped_expression = 37,
  sym_string = 38,
  sym_string_interpolation = 39,
  sym__break = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_definition_repeat1 = 42,
  aux_sym_record_declaration_repeat1 = 43,
  aux_sym_record_definition_repeat1 = 44,
  aux_sym_string_repeat1 = 45,
  anon_alias_sym_ = 46,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_name] = "name",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_operator] = "operator",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_DASH_GT] = "->",
  [anon_sym__] = "any",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_BSLASH_LPAREN] = "\\(",
  [sym_string_escaped] = "escaped",
  [sym_number] = "number",
  [sym_no_value] = "no_value",
  [sym_comment] = "comment",
  [sym_import_keyword] = "import_keyword",
  [anon_sym_SEMI] = ";",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_import] = "import",
  [sym_declaration] = "declaration",
  [sym_definition] = "definition",
  [sym__expression] = "_expression",
  [sym__record] = "_record",
  [sym_record_declaration] = "record_declaration",
  [sym_record_definition] = "record_definition",
  [sym__function_call] = "_function_call",
  [sym_prefix_call] = "prefix_call",
  [sym_infix_call] = "infix_call",
  [sym_operator_expression] = "operator_expression",
  [sym_function] = "function",
  [sym_pattern] = "pattern",
  [sym__grouped_expression] = "_grouped_expression",
  [sym_string] = "string",
  [sym_string_interpolation] = "interpolation",
  [sym__break] = "_break",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_definition_repeat1] = "definition_repeat1",
  [aux_sym_record_declaration_repeat1] = "record_declaration_repeat1",
  [aux_sym_record_definition_repeat1] = "record_definition_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [anon_alias_sym_] = "",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_name] = sym_name,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_operator] = sym_operator,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym__] = anon_sym__,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_BSLASH_LPAREN] = anon_sym_BSLASH_LPAREN,
  [sym_string_escaped] = sym_string_escaped,
  [sym_number] = sym_number,
  [sym_no_value] = sym_no_value,
  [sym_comment] = sym_comment,
  [sym_import_keyword] = sym_import_keyword,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_import] = sym_import,
  [sym_declaration] = sym_declaration,
  [sym_definition] = sym_definition,
  [sym__expression] = sym__expression,
  [sym__record] = sym__record,
  [sym_record_declaration] = sym_record_declaration,
  [sym_record_definition] = sym_record_definition,
  [sym__function_call] = sym__function_call,
  [sym_prefix_call] = sym_prefix_call,
  [sym_infix_call] = sym_infix_call,
  [sym_operator_expression] = sym_operator_expression,
  [sym_function] = sym_function,
  [sym_pattern] = sym_pattern,
  [sym__grouped_expression] = sym__grouped_expression,
  [sym_string] = sym_string,
  [sym_string_interpolation] = sym_string_interpolation,
  [sym__break] = sym__break,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_definition_repeat1] = aux_sym_definition_repeat1,
  [aux_sym_record_declaration_repeat1] = aux_sym_record_declaration_repeat1,
  [aux_sym_record_definition_repeat1] = aux_sym_record_definition_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [anon_alias_sym_] = anon_alias_sym_,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_string_escaped] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_no_value] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_import_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__record] = {
    .visible = false,
    .named = true,
  },
  [sym_record_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_record_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__function_call] = {
    .visible = false,
    .named = true,
  },
  [sym_prefix_call] = {
    .visible = true,
    .named = true,
  },
  [sym_infix_call] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym__grouped_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym__break] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_] = {
    .visible = true,
    .named = false,
  },
};

enum {
  field_name = 1,
  field_type = 2,
  field_value = 3,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[5] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_type, 2},
  [2] =
    {field_name, 0},
    {field_value, 2},
  [4] =
    {field_name, 0},
    {field_value, 3},
};

static TSSymbol ts_alias_sequences[5][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [4] = {
    [1] = anon_alias_sym_,
  },
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '.') ADVANCE(4);
      if (lookahead == ':') ADVANCE(7);
      if (lookahead == ';') ADVANCE(32);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead == '{') ADVANCE(9);
      if (lookahead == '}') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == '.') ADVANCE(4);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == '{') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(18);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '.') ADVANCE(13);
      if (lookahead == ';') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead == '{') ADVANCE(9);
      if (lookahead == '}') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('!' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          ('|' <= lookahead && lookahead <= '~')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == ')') ADVANCE(30);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_operator);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '(') ADVANCE(26);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(14);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '(') ADVANCE(26);
      if (lookahead == '"' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_BSLASH_LPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_string_escaped);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_no_value);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '_') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 2:
      if (lookahead == 'm') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == 'p') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_import_keyword);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 5, .external_lex_state = 1},
  [3] = {.lex_state = 5, .external_lex_state = 1},
  [4] = {.lex_state = 5, .external_lex_state = 1},
  [5] = {.lex_state = 5, .external_lex_state = 1},
  [6] = {.lex_state = 5, .external_lex_state = 1},
  [7] = {.lex_state = 5, .external_lex_state = 1},
  [8] = {.lex_state = 5, .external_lex_state = 1},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 5, .external_lex_state = 1},
  [29] = {.lex_state = 5, .external_lex_state = 1},
  [30] = {.lex_state = 5, .external_lex_state = 1},
  [31] = {.lex_state = 5, .external_lex_state = 1},
  [32] = {.lex_state = 5, .external_lex_state = 1},
  [33] = {.lex_state = 5, .external_lex_state = 1},
  [34] = {.lex_state = 5, .external_lex_state = 1},
  [35] = {.lex_state = 5, .external_lex_state = 1},
  [36] = {.lex_state = 5, .external_lex_state = 1},
  [37] = {.lex_state = 5, .external_lex_state = 1},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 5},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 5},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 0, .external_lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0, .external_lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0, .external_lex_state = 1},
  [63] = {.lex_state = 0, .external_lex_state = 1},
  [64] = {.lex_state = 0, .external_lex_state = 1},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0, .external_lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0, .external_lex_state = 1},
  [69] = {.lex_state = 0, .external_lex_state = 1},
  [70] = {.lex_state = 0, .external_lex_state = 1},
  [71] = {.lex_state = 0, .external_lex_state = 1},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0, .external_lex_state = 1},
  [74] = {.lex_state = 0, .external_lex_state = 1},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0, .external_lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0, .external_lex_state = 1},
  [82] = {.lex_state = 0, .external_lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0, .external_lex_state = 1},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0, .external_lex_state = 1},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
};

enum {
  ts_external_token__newline = 0,
};

static TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
};

static bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
  },
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_no_value] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_import_keyword] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(98),
    [sym__statement] = STATE(74),
    [sym_import] = STATE(74),
    [sym_declaration] = STATE(74),
    [sym_definition] = STATE(74),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_name] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [sym_import_keyword] = ACTIONS(9),
  },
  [2] = {
    [sym__expression] = STATE(5),
    [sym__record] = STATE(5),
    [sym_record_declaration] = STATE(5),
    [sym_record_definition] = STATE(5),
    [sym__function_call] = STATE(5),
    [sym_prefix_call] = STATE(5),
    [sym_infix_call] = STATE(5),
    [sym_operator_expression] = STATE(5),
    [sym_function] = STATE(5),
    [sym__grouped_expression] = STATE(5),
    [sym_string] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_name] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(17),
    [sym_operator] = ACTIONS(19),
    [anon_sym_BSLASH] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_number] = ACTIONS(13),
    [sym_no_value] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(11),
    [sym__newline] = ACTIONS(11),
  },
  [3] = {
    [sym__expression] = STATE(5),
    [sym__record] = STATE(5),
    [sym_record_declaration] = STATE(5),
    [sym_record_definition] = STATE(5),
    [sym__function_call] = STATE(5),
    [sym_prefix_call] = STATE(5),
    [sym_infix_call] = STATE(5),
    [sym_operator_expression] = STATE(5),
    [sym_function] = STATE(5),
    [sym__grouped_expression] = STATE(5),
    [sym_string] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_name] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(17),
    [sym_operator] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_number] = ACTIONS(13),
    [sym_no_value] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(25),
    [sym__newline] = ACTIONS(25),
  },
  [4] = {
    [sym__expression] = STATE(5),
    [sym__record] = STATE(5),
    [sym_record_declaration] = STATE(5),
    [sym_record_definition] = STATE(5),
    [sym__function_call] = STATE(5),
    [sym_prefix_call] = STATE(5),
    [sym_infix_call] = STATE(5),
    [sym_operator_expression] = STATE(5),
    [sym_function] = STATE(5),
    [sym__grouped_expression] = STATE(5),
    [sym_string] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_name] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(17),
    [sym_operator] = ACTIONS(19),
    [anon_sym_BSLASH] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_number] = ACTIONS(13),
    [sym_no_value] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(29),
    [sym__newline] = ACTIONS(29),
  },
  [5] = {
    [sym__expression] = STATE(5),
    [sym__record] = STATE(5),
    [sym_record_declaration] = STATE(5),
    [sym_record_definition] = STATE(5),
    [sym__function_call] = STATE(5),
    [sym_prefix_call] = STATE(5),
    [sym_infix_call] = STATE(5),
    [sym_operator_expression] = STATE(5),
    [sym_function] = STATE(5),
    [sym__grouped_expression] = STATE(5),
    [sym_string] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_name] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(33),
    [sym_operator] = ACTIONS(33),
    [anon_sym_BSLASH] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [sym_number] = ACTIONS(31),
    [sym_no_value] = ACTIONS(31),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(31),
    [sym__newline] = ACTIONS(31),
  },
  [6] = {
    [sym__expression] = STATE(5),
    [sym__record] = STATE(5),
    [sym_record_declaration] = STATE(5),
    [sym_record_definition] = STATE(5),
    [sym__function_call] = STATE(5),
    [sym_prefix_call] = STATE(5),
    [sym_infix_call] = STATE(5),
    [sym_operator_expression] = STATE(5),
    [sym_function] = STATE(5),
    [sym__grouped_expression] = STATE(5),
    [sym_string] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_name] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(17),
    [sym_operator] = ACTIONS(19),
    [anon_sym_BSLASH] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_number] = ACTIONS(13),
    [sym_no_value] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(35),
    [sym__newline] = ACTIONS(35),
  },
  [7] = {
    [sym__expression] = STATE(5),
    [sym__record] = STATE(5),
    [sym_record_declaration] = STATE(5),
    [sym_record_definition] = STATE(5),
    [sym__function_call] = STATE(5),
    [sym_prefix_call] = STATE(5),
    [sym_infix_call] = STATE(5),
    [sym_operator_expression] = STATE(5),
    [sym_function] = STATE(5),
    [sym__grouped_expression] = STATE(5),
    [sym_string] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_name] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(17),
    [sym_operator] = ACTIONS(19),
    [anon_sym_BSLASH] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_number] = ACTIONS(13),
    [sym_no_value] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(37),
    [sym__newline] = ACTIONS(37),
  },
  [8] = {
    [sym__expression] = STATE(5),
    [sym__record] = STATE(5),
    [sym_record_declaration] = STATE(5),
    [sym_record_definition] = STATE(5),
    [sym__function_call] = STATE(5),
    [sym_prefix_call] = STATE(5),
    [sym_infix_call] = STATE(5),
    [sym_operator_expression] = STATE(5),
    [sym_function] = STATE(5),
    [sym__grouped_expression] = STATE(5),
    [sym_string] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_name] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(17),
    [sym_operator] = ACTIONS(19),
    [anon_sym_BSLASH] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_number] = ACTIONS(13),
    [sym_no_value] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(39),
    [sym__newline] = ACTIONS(39),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_RPAREN,
    ACTIONS(49), 1,
      sym_operator,
    ACTIONS(51), 1,
      anon_sym_BSLASH,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(14), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [40] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_RPAREN,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_operator,
    ACTIONS(51), 1,
      anon_sym_BSLASH,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(14), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [80] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_RPAREN,
    ACTIONS(27), 1,
      sym_operator,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_BSLASH,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(14), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [120] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_operator,
    ACTIONS(51), 1,
      anon_sym_BSLASH,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(55), 1,
      anon_sym_RPAREN,
    ACTIONS(41), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(14), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [160] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_RPAREN,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_operator,
    ACTIONS(51), 1,
      anon_sym_BSLASH,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(14), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [200] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(31), 6,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
    STATE(14), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [230] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_operator,
    ACTIONS(51), 1,
      anon_sym_BSLASH,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 1,
      anon_sym_RPAREN,
    ACTIONS(41), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(14), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [270] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_BSLASH,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      sym_operator,
    ACTIONS(59), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(9), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [307] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_BSLASH,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      sym_operator,
    ACTIONS(63), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(12), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [344] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_BSLASH,
    ACTIONS(67), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(2), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [378] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_BSLASH,
    ACTIONS(71), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(4), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [412] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_BSLASH,
    ACTIONS(73), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(6), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [446] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 1,
      anon_sym_BSLASH,
    ACTIONS(75), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(15), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [480] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_BSLASH,
    ACTIONS(79), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(8), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [514] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_BSLASH,
    ACTIONS(81), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(3), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [548] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 1,
      anon_sym_BSLASH,
    ACTIONS(83), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(13), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [582] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 1,
      anon_sym_BSLASH,
    ACTIONS(85), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(11), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [616] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 1,
      anon_sym_BSLASH,
    ACTIONS(87), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(10), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [650] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_BSLASH,
    ACTIONS(89), 3,
      sym_name,
      sym_number,
      sym_no_value,
    STATE(7), 11,
      sym__expression,
      sym__record,
      sym_record_declaration,
      sym_record_definition,
      sym__function_call,
      sym_prefix_call,
      sym_infix_call,
      sym_operator_expression,
      sym_function,
      sym__grouped_expression,
      sym_string,
  [684] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(91), 9,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
      anon_sym_SEMI,
  [704] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(95), 9,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
      anon_sym_SEMI,
  [724] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(99), 9,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
      anon_sym_SEMI,
  [744] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(103), 9,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
      anon_sym_SEMI,
  [764] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(107), 9,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
      anon_sym_SEMI,
  [784] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(111), 9,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
      anon_sym_SEMI,
  [804] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(115), 9,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
      anon_sym_SEMI,
  [824] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(119), 9,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
      anon_sym_SEMI,
  [844] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(123), 9,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
      anon_sym_SEMI,
  [864] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(127), 9,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
      anon_sym_SEMI,
  [884] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(111), 6,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
  [901] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(103), 6,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
  [918] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(91), 6,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
  [935] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(107), 6,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
  [952] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(115), 6,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
  [969] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(127), 6,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
  [986] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(99), 6,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
  [1003] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(119), 6,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
  [1020] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(123), 6,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
  [1037] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 3,
      anon_sym_LPAREN,
      sym_operator,
      anon_sym_BSLASH,
    ACTIONS(95), 6,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      sym_name,
      anon_sym_DQUOTE,
      sym_number,
      sym_no_value,
  [1054] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_name,
    ACTIONS(9), 1,
      sym_import_keyword,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    STATE(81), 4,
      sym__statement,
      sym_import,
      sym_declaration,
      sym_definition,
  [1073] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_name,
    ACTIONS(9), 1,
      sym_import_keyword,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
    STATE(81), 4,
      sym__statement,
      sym_import,
      sym_declaration,
      sym_definition,
  [1092] = 5,
    ACTIONS(135), 1,
      anon_sym_DQUOTE,
    ACTIONS(139), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(141), 1,
      sym_comment,
    ACTIONS(137), 2,
      aux_sym_string_token1,
      sym_string_escaped,
    STATE(55), 2,
      sym_string_interpolation,
      aux_sym_string_repeat1,
  [1110] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_name,
    ACTIONS(9), 1,
      sym_import_keyword,
    STATE(81), 4,
      sym__statement,
      sym_import,
      sym_declaration,
      sym_definition,
  [1126] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym__,
      sym_name,
    ACTIONS(146), 2,
      anon_sym_EQ,
      anon_sym_DASH_GT,
    STATE(52), 2,
      sym_pattern,
      aux_sym_definition_repeat1,
  [1142] = 5,
    ACTIONS(139), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(141), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
    ACTIONS(150), 2,
      aux_sym_string_token1,
      sym_string_escaped,
    STATE(50), 2,
      sym_string_interpolation,
      aux_sym_string_repeat1,
  [1160] = 5,
    ACTIONS(139), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(141), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_DQUOTE,
    ACTIONS(154), 2,
      aux_sym_string_token1,
      sym_string_escaped,
    STATE(57), 2,
      sym_string_interpolation,
      aux_sym_string_repeat1,
  [1178] = 5,
    ACTIONS(141), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_DQUOTE,
    ACTIONS(161), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(158), 2,
      aux_sym_string_token1,
      sym_string_escaped,
    STATE(55), 2,
      sym_string_interpolation,
      aux_sym_string_repeat1,
  [1196] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_COLON,
    ACTIONS(168), 1,
      anon_sym_EQ,
    ACTIONS(164), 2,
      anon_sym__,
      sym_name,
    STATE(75), 2,
      sym_pattern,
      aux_sym_definition_repeat1,
  [1214] = 5,
    ACTIONS(139), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(141), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_DQUOTE,
    ACTIONS(137), 2,
      aux_sym_string_token1,
      sym_string_escaped,
    STATE(55), 2,
      sym_string_interpolation,
      aux_sym_string_repeat1,
  [1232] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      aux_sym_record_definition_repeat1,
    STATE(80), 1,
      sym__break,
    ACTIONS(174), 2,
      sym__newline,
      anon_sym_SEMI,
  [1249] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_DASH_GT,
    ACTIONS(164), 2,
      anon_sym__,
      sym_name,
    STATE(52), 2,
      sym_pattern,
      aux_sym_definition_repeat1,
  [1264] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      aux_sym_record_definition_repeat1,
    STATE(93), 1,
      sym__break,
    ACTIONS(180), 2,
      sym__newline,
      anon_sym_SEMI,
  [1281] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_DASH_GT,
    ACTIONS(164), 2,
      anon_sym__,
      sym_name,
    STATE(59), 2,
      sym_pattern,
      aux_sym_definition_repeat1,
  [1296] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      aux_sym_record_definition_repeat1,
    STATE(91), 1,
      sym__break,
    ACTIONS(187), 2,
      sym__newline,
      anon_sym_SEMI,
  [1313] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_record_declaration_repeat1,
    STATE(90), 1,
      sym__break,
    ACTIONS(191), 2,
      sym__newline,
      anon_sym_SEMI,
  [1330] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
    STATE(51), 1,
      sym__break,
    STATE(64), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(195), 2,
      sym__newline,
      anon_sym_SEMI,
  [1347] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_DASH_GT,
    ACTIONS(164), 2,
      anon_sym__,
      sym_name,
    STATE(52), 2,
      sym_pattern,
      aux_sym_definition_repeat1,
  [1362] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      aux_sym_record_definition_repeat1,
    STATE(89), 1,
      sym__break,
    ACTIONS(202), 2,
      sym__newline,
      anon_sym_SEMI,
  [1379] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_EQ,
    ACTIONS(164), 2,
      anon_sym__,
      sym_name,
    STATE(75), 2,
      sym_pattern,
      aux_sym_definition_repeat1,
  [1394] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    STATE(49), 1,
      sym__break,
    STATE(64), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(204), 2,
      sym__newline,
      anon_sym_SEMI,
  [1411] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_record_declaration_repeat1,
    STATE(94), 1,
      sym__break,
    ACTIONS(208), 2,
      sym__newline,
      anon_sym_SEMI,
  [1428] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      aux_sym_record_declaration_repeat1,
    STATE(87), 1,
      sym__break,
    ACTIONS(213), 2,
      sym__newline,
      anon_sym_SEMI,
  [1445] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
    STATE(76), 1,
      aux_sym_record_declaration_repeat1,
    STATE(79), 1,
      sym__break,
    ACTIONS(217), 2,
      sym__newline,
      anon_sym_SEMI,
  [1462] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_DASH_GT,
    ACTIONS(164), 2,
      anon_sym__,
      sym_name,
    STATE(65), 2,
      sym_pattern,
      aux_sym_definition_repeat1,
  [1477] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      aux_sym_record_definition_repeat1,
    STATE(83), 1,
      sym__break,
    ACTIONS(223), 2,
      sym__newline,
      anon_sym_SEMI,
  [1494] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      ts_builtin_sym_end,
    STATE(48), 1,
      sym__break,
    STATE(68), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(227), 2,
      sym__newline,
      anon_sym_SEMI,
  [1511] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_EQ,
    ACTIONS(164), 2,
      anon_sym__,
      sym_name,
    STATE(52), 2,
      sym_pattern,
      aux_sym_definition_repeat1,
  [1526] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_record_declaration_repeat1,
    STATE(85), 1,
      sym__break,
    ACTIONS(233), 2,
      sym__newline,
      anon_sym_SEMI,
  [1543] = 2,
    ACTIONS(141), 1,
      sym_comment,
    ACTIONS(235), 4,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      anon_sym_BSLASH_LPAREN,
      sym_string_escaped,
  [1553] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 2,
      anon_sym__,
      sym_name,
    ACTIONS(239), 2,
      anon_sym_EQ,
      anon_sym_DASH_GT,
  [1565] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_RBRACE,
    ACTIONS(241), 1,
      sym_name,
    STATE(84), 1,
      sym_declaration,
  [1578] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_name,
    ACTIONS(245), 1,
      anon_sym_RBRACE,
    STATE(88), 1,
      sym_definition,
  [1591] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1600] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1609] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
    ACTIONS(243), 1,
      sym_name,
    STATE(88), 1,
      sym_definition,
  [1622] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 3,
      sym__newline,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1631] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_name,
    ACTIONS(249), 1,
      anon_sym_RBRACE,
    STATE(84), 1,
      sym_declaration,
  [1644] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_name,
    STATE(71), 1,
      sym_declaration,
    STATE(73), 1,
      sym_definition,
  [1657] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
    ACTIONS(241), 1,
      sym_name,
    STATE(84), 1,
      sym_declaration,
  [1670] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 3,
      sym__newline,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [1679] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    ACTIONS(243), 1,
      sym_name,
    STATE(88), 1,
      sym_definition,
  [1692] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_name,
    ACTIONS(253), 1,
      anon_sym_RBRACE,
    STATE(84), 1,
      sym_declaration,
  [1705] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_name,
    ACTIONS(255), 1,
      anon_sym_RBRACE,
    STATE(88), 1,
      sym_definition,
  [1718] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_name,
    STATE(66), 1,
      sym_definition,
    STATE(70), 1,
      sym_declaration,
  [1731] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_name,
    STATE(88), 1,
      sym_definition,
  [1741] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_name,
    STATE(84), 1,
      sym_declaration,
  [1751] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_RPAREN,
  [1758] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_COLON,
  [1765] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_RPAREN,
  [1772] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      ts_builtin_sym_end,
  [1779] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      sym_name,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 40,
  [SMALL_STATE(11)] = 80,
  [SMALL_STATE(12)] = 120,
  [SMALL_STATE(13)] = 160,
  [SMALL_STATE(14)] = 200,
  [SMALL_STATE(15)] = 230,
  [SMALL_STATE(16)] = 270,
  [SMALL_STATE(17)] = 307,
  [SMALL_STATE(18)] = 344,
  [SMALL_STATE(19)] = 378,
  [SMALL_STATE(20)] = 412,
  [SMALL_STATE(21)] = 446,
  [SMALL_STATE(22)] = 480,
  [SMALL_STATE(23)] = 514,
  [SMALL_STATE(24)] = 548,
  [SMALL_STATE(25)] = 582,
  [SMALL_STATE(26)] = 616,
  [SMALL_STATE(27)] = 650,
  [SMALL_STATE(28)] = 684,
  [SMALL_STATE(29)] = 704,
  [SMALL_STATE(30)] = 724,
  [SMALL_STATE(31)] = 744,
  [SMALL_STATE(32)] = 764,
  [SMALL_STATE(33)] = 784,
  [SMALL_STATE(34)] = 804,
  [SMALL_STATE(35)] = 824,
  [SMALL_STATE(36)] = 844,
  [SMALL_STATE(37)] = 864,
  [SMALL_STATE(38)] = 884,
  [SMALL_STATE(39)] = 901,
  [SMALL_STATE(40)] = 918,
  [SMALL_STATE(41)] = 935,
  [SMALL_STATE(42)] = 952,
  [SMALL_STATE(43)] = 969,
  [SMALL_STATE(44)] = 986,
  [SMALL_STATE(45)] = 1003,
  [SMALL_STATE(46)] = 1020,
  [SMALL_STATE(47)] = 1037,
  [SMALL_STATE(48)] = 1054,
  [SMALL_STATE(49)] = 1073,
  [SMALL_STATE(50)] = 1092,
  [SMALL_STATE(51)] = 1110,
  [SMALL_STATE(52)] = 1126,
  [SMALL_STATE(53)] = 1142,
  [SMALL_STATE(54)] = 1160,
  [SMALL_STATE(55)] = 1178,
  [SMALL_STATE(56)] = 1196,
  [SMALL_STATE(57)] = 1214,
  [SMALL_STATE(58)] = 1232,
  [SMALL_STATE(59)] = 1249,
  [SMALL_STATE(60)] = 1264,
  [SMALL_STATE(61)] = 1281,
  [SMALL_STATE(62)] = 1296,
  [SMALL_STATE(63)] = 1313,
  [SMALL_STATE(64)] = 1330,
  [SMALL_STATE(65)] = 1347,
  [SMALL_STATE(66)] = 1362,
  [SMALL_STATE(67)] = 1379,
  [SMALL_STATE(68)] = 1394,
  [SMALL_STATE(69)] = 1411,
  [SMALL_STATE(70)] = 1428,
  [SMALL_STATE(71)] = 1445,
  [SMALL_STATE(72)] = 1462,
  [SMALL_STATE(73)] = 1477,
  [SMALL_STATE(74)] = 1494,
  [SMALL_STATE(75)] = 1511,
  [SMALL_STATE(76)] = 1526,
  [SMALL_STATE(77)] = 1543,
  [SMALL_STATE(78)] = 1553,
  [SMALL_STATE(79)] = 1565,
  [SMALL_STATE(80)] = 1578,
  [SMALL_STATE(81)] = 1591,
  [SMALL_STATE(82)] = 1600,
  [SMALL_STATE(83)] = 1609,
  [SMALL_STATE(84)] = 1622,
  [SMALL_STATE(85)] = 1631,
  [SMALL_STATE(86)] = 1644,
  [SMALL_STATE(87)] = 1657,
  [SMALL_STATE(88)] = 1670,
  [SMALL_STATE(89)] = 1679,
  [SMALL_STATE(90)] = 1692,
  [SMALL_STATE(91)] = 1705,
  [SMALL_STATE(92)] = 1718,
  [SMALL_STATE(93)] = 1731,
  [SMALL_STATE(94)] = 1741,
  [SMALL_STATE(95)] = 1751,
  [SMALL_STATE(96)] = 1758,
  [SMALL_STATE(97)] = 1765,
  [SMALL_STATE(98)] = 1772,
  [SMALL_STATE(99)] = 1779,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 3, .production_id = 2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_infix_call, 3),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_infix_call, 3),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 4, .production_id = 3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_call, 2),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_call, 2),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 3),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, .production_id = 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_declaration, 4),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_declaration, 4),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_definition, 5),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_definition, 5),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_definition, 4),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_definition, 4),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__grouped_expression, 3),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__grouped_expression, 3),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 3, .production_id = 4),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator_expression, 3, .production_id = 4),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_definition, 3),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_definition, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_declaration, 3),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_declaration, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_declaration, 5),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_declaration, 5),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_definition_repeat1, 2), SHIFT_REPEAT(78),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_definition_repeat1, 2),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [158] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(55),
  [161] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(21),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_definition_repeat1, 2),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_definition_repeat1, 2), SHIFT_REPEAT(93),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(51),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_declaration_repeat1, 2),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_declaration_repeat1, 2), SHIFT_REPEAT(94),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_interpolation, 3),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 1),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [261] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_nova_external_scanner_create(void);
void tree_sitter_nova_external_scanner_destroy(void *);
bool tree_sitter_nova_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_nova_external_scanner_serialize(void *, char *);
void tree_sitter_nova_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_nova(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_name,
    .external_scanner = {
      (const bool *)ts_external_scanner_states,
      ts_external_scanner_symbol_map,
      tree_sitter_nova_external_scanner_create,
      tree_sitter_nova_external_scanner_destroy,
      tree_sitter_nova_external_scanner_scan,
      tree_sitter_nova_external_scanner_serialize,
      tree_sitter_nova_external_scanner_deserialize,
    },
    .field_count = FIELD_COUNT,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .field_names = ts_field_names,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
